import type { Continent, Location } from '../types';
import raw from './panoramas.json';

/**
 * Panorama pool, generated by `scripts/build-dataset.py` from Panoramax
 * (https://panoramax.xyz) — open, keyless, CC-licensed street-level imagery.
 * Every entry is equirectangular, so every round is a real look-around.
 *
 * Stored compactly: `h` hosts, `p` place labels, `i` rows of
 * [hostIndex, path, lat, lng, placeIndex].
 */
interface Compact {
  h: string[];
  p: [string, string, string][];
  i: [number, string, number, number, number][];
}

const data = raw as Compact;

export const LOCATIONS: Location[] = data.i.map(([host, path, lat, lng, place], id) => {
  const [name, country, continent] = data.p[place];
  return { id, url: data.h[host] + path, name, country, continent: continent as Continent, lat, lng };
});

export const CONTINENTS: Continent[] = [
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'Oceania',
  'South America',
];

/**
 * A country needs a handful of distinct panoramas before a ten-round game in
 * it is worth playing; below that the same image would come round repeatedly.
 */
export const MIN_COUNTRY_PANORAMAS = 5;

export const COUNTRIES: { name: string; continent: Continent; count: number }[] = (() => {
  const map = new Map<string, { name: string; continent: Continent; count: number }>();
  for (const loc of LOCATIONS) {
    const found = map.get(loc.country);
    if (found) found.count += 1;
    else map.set(loc.country, { name: loc.country, continent: loc.continent, count: 1 });
  }
  return [...map.values()]
    .filter((c) => c.count >= MIN_COUNTRY_PANORAMAS)
    .sort((a, b) => a.name.localeCompare(b.name));
})();
